# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "."
    schedule:
      interval: "weekly"
    commit-message:
      prefix: chore(deps)
      prefix-development: "fix(deps)"
    open-pull-requests-limit: 5
    target-branch: "dev"